apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-ui
  labels:
    app: {{ .Release.Name }}-todo-ui
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-todo-ui
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-todo-ui
    spec:
      containers:
      - name: todo-ui
        image: devcontainerregistry8210.azurecr.io/todo-ui:v1
        ports:
        - containerPort: 80
